service:
  name: "default-service"
  replicaCount: 2
  image:
    repository: "cr.yandex/crpoda1shi1fqfki3em1/default-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  ports:
    containerPort: 8080
    servicePort: 80
  env: []
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
ingress:
  enabled: true
  host: "default.127.0.0.1.nip.io"
  path: "/"
