apiVersion: v1
kind: Service
meta
  name: {{ .Values.service.name }}-service
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.ports.servicePort }}
    targetPort: {{ .Values.service.ports.containerPort }}
  type: ClusterIP
